from PIL import Image
import matplotlib.pyplot as plt

def visualize_random_dots(prng, width=550, height=600, threshold=0.5):
    ''' Visualize a random pattern generated by the given PRNG '''
    img = Image.new('RGB', (width, height))
    pixels = img.load()


    for y in range(height):
        for x in range(width):
            rnd = prng.next(1)[0] / 255
            color = (255, 255, 255) if rnd < threshold else (0, 0, 0)
            pixels[x, y] = color


    img.show()

def visualize_wave(prng1, prng2, width=600, step=20, amplitude=50, baseline1=100, baseline2=300):
    ''' Visualize wave patterns generated by two PRNGs using matplotlib '''
    xs = list(range(0, width + 1, step))

    def noise(prng, base):
        return [base + prng.next(1)[0] / 255 * amplitude for _ in xs]

    ys1 = noise(prng1, baseline1)
    ys2 = noise(prng2, baseline2)

    plt.plot(xs, ys1, label="PRNG without refresh")
    plt.plot(xs, ys2, label="PRNG with refresh")
    plt.ylim(0, baseline2 + amplitude + 50)
    plt.title("Seedless PRNG comparison")
    plt.legend()
    plt.grid(True)
    plt.show()