from PIL import Image

def visualize_random_pattern(prng, width=550, height=600, threshold=0.5):
    ''' Visualize a random pattern generated by the given PRNG '''
    img = Image.new('RGB', (width, height))
    pixels = img.load()


    for y in range(height):
        for x in range(width):
            rnd = prng.next(1)[0] / 255
            color = (255, 255, 255) if rnd < threshold else (0, 0, 0)
            pixels[x, y] = color


    img.show()